# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: trigger single Job
        uses: actions/checkout@v2
        with:
          url: "http://cicd001.fms.ogintegration.us:8080"
          user: "jenkins"
          token: ${{ secrets.TOKEN }}
          job: "java-build-dev001"
